<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="6627" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:41Z">
    <groups>
    </groups>
    <test name="ApiAutoDemo" duration-ms="6627" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:41Z">
      <class name="com.qa.tests.GetTest01">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="setUp" is-config="true" duration-ms="88" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Test01()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="Test01" duration-ms="1" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test01 -->
        <test-method status="PASS" signature="Test02()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="Test02" duration-ms="0" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test02 -->
        <test-method status="PASS" signature="Test03()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="Test03" duration-ms="1" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test03 -->
        <test-method status="FAIL" signature="Test04()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="Test04" duration-ms="1042" started-at="2021-05-15T07:43:34Z" finished-at="2021-05-15T07:43:35Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.qa.tests.GetTest01.Test04() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.qa.tests.GetTest01.Test04() didn't finish within the time-out 1000
at java.lang.Thread.interrupt(Thread.java:916)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test04 -->
        <test-method status="PASS" signature="getListUsers()[pri:0, instance:com.qa.tests.GetTest01@e580929]" name="getListUsers" duration-ms="5322" started-at="2021-05-15T07:43:35Z" finished-at="2021-05-15T07:43:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListUsers -->
      </class> <!-- com.qa.tests.GetTest01 -->
    </test> <!-- ApiAutoDemo -->
  </suite> <!-- Default Suite -->
</testng-results>
